# Generated by Django 5.1.4 on 2024-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.CharField(max_length=100)),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=1000)),
                ('previous_hash', models.CharField(max_length=1000)),
                ('transactions', models.CharField(max_length=50000)),
            ],
        ),
    ]
